### PR TITLE
Adjust go binding

### PR DESCRIPTION
**Pull request by schrodit**
**What this PR does / why we need it**:

adjusts the go binding to the local and external res merge.

adds another access type `ociLayer` that specifies the blob access to another oci layer in the current component descriptors oci manifest.
```
access:
  type: ociLayer
  layer: 2
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Comment by ccwienk** [comment]
>   type: ociLayer
while this follows the internal technical naming, it does not well express our intended semantics (for us, this is a blob, stored in a OCI repository). So how about naming it `ociBlob` instead?
/cc @mandelsoft

**Comment by schrodit** [comment]
oci blob sounds good.
I also thought that we might need an additional `ref` field if we want to reference a blob from another manifest wdyt?

```
access:
  type: ociBlob
  ref: host/path/manifest:1.0.0 # optional will be defaulted to current component descriptor manifest
  layer: 2
```

**Comment by ccwienk** [comment]
@schrodit : I would prefer to always write the `ref` - it may be omitted from the "end-user", and injected if it is local. Although I think I remember @mandelsoft had some reasons for not doing this. how about an additional attribute `relation`, which again (similar to resources) could be `local` or `external` (in the first case, this would mean the ref is implicitly equivalent to the one from the CD).

on additional note, I would prefer not to allow referencing the layer by idx - let us always use content-adressing, where possible (i.e. hash-digest).

**Comment by schrodit** [comment]
the `ociBlob` access is now updated to:
```
access:
  type: ociBlob
  ref: host/path/artifact:v1.0.0
  mediaType: application/tar
  digest: ab453
  size: 123
```
@ccwienk PTAL

**Review by ccwienk — APPROVED** [review]

**Pull request merged**
